In [9]:
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score

reg = linear_model.LinearRegression(fit_intercept=True)

data = np.array([[1, 2, 3, 4, 5, 6, 7],[1.8, 4.3, 6.2,  5, 11, 11, 15]])

x = data[0,:].reshape(7,1)
y = data[1,:]
 
 
reg.fit(x,y)

print('Coefficients: \n', reg.coef_)
print('Intercept: \n', reg.intercept_)
print('Score: \n' , reg.score(x, y))
print('Mean squared error: %.2f' % mean_squared_error(x, y))
print('Coefficient of determination: %.2f' % r2_score(x, y))



Coefficients: 
 [2.06428571]
Intercept: 
 -0.5000000000000009
Score: 
 0.9111050507254281
Mean squared error: 20.31
Coefficient of determination: -4.08


In [ ]:
xTest = np.array([[4],[5],[6]])
xTest

ytest =  np.array([[8],[10],[12]])

preds = reg.predict(xTest)
preds

print("Mean squared error: %.2f" % mean_squared_error(ytest,preds))

print("Variance score: %.2f" % r2_score(ytest,preds))


plt.scatter(xTest,preds, color='black')
plt.plot(xTest,preds,color='blue', linewidth=3)

plt.show()

In [86]:
x.shape

(7, 1)

In [87]:
y

array([ 1.8,  4.3,  6.2,  5. , 11. , 11. , 15. ])

In [88]:
y.shape

(7,)

In [77]:
x

array([[1., 2., 3., 4., 5., 6., 7.]])

In [68]:
z

array([[1., 2., 3., 4., 5., 6., 7.]])

In [69]:
z.shape

(1, 7)