In [2]:
import numpy as np
arr =  np.array([1,2,3,4,5])
print(arr)
arr.shape

[1 2 3 4 5]


(5,)

In [4]:
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [7]:
arr =  np.array([[1,2,3,4,5], [2,4,6,8,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]


In [10]:
arr[0,0:3]

array([1, 2, 3])

In [11]:
arr[1,0:3]

array([2, 4, 6])

In [12]:
arr[0,:]

array([1, 2, 3, 4, 5])

In [13]:
arr[1:]

array([[ 2,  4,  6,  8, 10]])

In [14]:
arr[:,3]

array([4, 8])